name: Find Pull Request
author: juliangruber
description: 'A GitHub Action for finding pull requests'
branding:
  icon: 'git-pull-request'
  color: purple
inputs:
  github-token:
    description: 'GitHub Token'
    required: false
    default: ${{ github.token }}
  branch:
    description: |
      The name of the branch from which the pull request was opened. For cross-repository pull requests namespace the
      branch with user or organization name, i.e. 'user:branch-name' or 'org:branch-name'.
    required: false
  base:
    description: 'The base branch name of the Pull Request'
    required: false
  author:
    description: 'The author of the Pull Request'
    required: false
  state:
    description: 'The state of the Pull Request. Can be either `open`, `closed` or `all`.'
    required: false
    default: open
  sort:
    description: |
      What to sort results by. Can be either `created`, `updated`, `popularity`
      (comment count) or `long-running` (age, filtering by pulls updated in the last month).
    required: false
  direction:
    description: 'The direction of the sort. Can be either `asc` or `desc`.'
    default: 'desc'
    required: false

outputs:
  number:
    description: The Pull Request's number if one was found (e.g. '345' for #345)
  head-sha:
    description: The Pull Request's head sha if one was found
runs:
  using: 'node12'
  main: 'dist/index.js'
